export const answers = [
    "Kyllä, poliisiputkassa.",
    "Ainakin aamulypsyn jälkeen.",
    "Ah, tämä tuli niin äkkiä, mutta jos kysyisit kahden kesken, vastaisin »kyllä».",
    "Kyllä, varsinkin ellen ole nukkunut yöllä.",
    "Sellaista tapahtuu vain kun syön kaurapuuroa.",
    "Toisinaan, ellen saa aikaani muuten kulumaan.",
    "Kyllä, sillä olen nähnyt Tauno Palonkin tekevän sillä tavalla.",
    "Kyllä, ellei minua enää mikään muu voi huvittaa.",
    "Kylläpä vaan, aamusta iltaan!",
    "Kysy vain kuinka paljon!",
    "Se on tullut minulle melkein tavaksi.",
    "Ainoastaan maanantaisin.",
    "Vain täysikuun aikana.",
    "Ainoastaan mätäkuussa.",
    "Vain ollessani hyvällä tuulella.",
    "Hyvin paljon mahdollista, varsinkin suojasäällä.",
    "Tuskin mikään on mukavampaa kuin se.",
    "Kyllä, rikkaruohoja kitkiessä.",
    "Ei ei - omatuntoni ei salli minun tehdä sitä.",
    "Toisinaan, jos mieleni tekee oikein kovasti lakritsia.",
    "Keväisin, tyydyttääkseni runollista kaipuutani.",
    "Silloin, jos hammastani särkee yöllä.",
    "Viimeksi eilen.",
    "Vain syntymäpäiväni kunniaksi.",
    "Ainoastaan silloin kun poliisi ei huomaa.",
    "Kuunnellessani torvisoittoa.",
    "Mielummin Ambomaalla.",
    "Silloin kun olen kasiaisia keräämässä.",
    "Vasta vuonna 1999.",
    "Kovasti paljon, jos vain olen sattunut saamaan saippuaa silmiini.",
    "Kesällä tallinparvessa.",
    "Välistä sängyn alla.",
    "Joskus karusellissa kylläkin.",
    "Melkein aina.",
    "Tottakai sateella.",
    "No täytyypä myöntää kyllä, jos näen oikein nätin tytön!",
    "Kyllä, varsinkin keskiyöllä.",
    "Vain silloin kun minun pitää lähteä kyläilemään.",
    "Kyllä vain, kun olen syönyt itseni kylläiseksi.",
    "Minusta se on hyvin sopimatonta!",
    "Mahdollisesti, jos olen ruokkimassa sikoja.",
    "Useinkin, vaikkei siitä puhuta.",
    "Ei sitten ikinä eikä missään tapauksessa!",
    "Ihan varmasti silloin, jos olen tipahtanut tikapuilta.",
    "Jos minulle maksetaan siitä viisi markkaa.",
    "Totta kai, joka kerta kun harjoittelen ajamaan polkupyörällä.",
    "Ei vaikka vähän maksettaisi.",
    "Siihen tunnen olevani täysin kykenemätön.",
    "Kyllä, kun ei satu olemaan muuta tekemistä.",
    "Jos minut on pantu istumaan laiskanläksylle.",
    "Ei kissa vieköön! Siitä on jo ainakin kymmenen vuotta aikaa.",
    "Liimaillessani postimerkkejä iltaisin.",
    "Kyllä hyvässä seurassa.",
    "Kyllä, seitsemänkymmentä seitsemän kertaa.",
    "Tietysti, jos äiti käskee.",
    "Joka vuosi, kun syysillat pimenevät.",
    "Kovasti - nimenomaan saunassa.",
    "Juupa juu, ellen ole saanut koko päivänä ruokaa.",
    "Varmasti, jos olen syönyt erehdyksessä suolaa sokerin asemasta.",
    "Ei muuten kuin maitojonossa.",
    "Kyllä, varsinkin aamutuimaan!",
    "Ei kissa vieköön.",
    "Aina kun minun täytyy pestä jalkani.",
    "Sellaiseen minä olen liian lihava.",
    "Silloin tällöin vinttikamarissa.",
    "Se on mielestäni erittäin terveellistä.",
    "Eniten kylvyssä.",
    "Kyllä, kun olen tehnyt tupakkalakon.",
    "Sen verran ettei se ole tullut tavaksi.",
    "Ylihuomenna aion yrittää.",
    "Joskus, kun haluan saada nikotuksen pois.",
    "Ainoastaan kun hikoilen liikaa.",
    "Jos kieltäisin, niin valehtelisin.",
    "Yksinomaan ollessani naisseurassa.",
    "Tämän tästä, mutta se johtuu siitä, että olen syönyt liikaa papusoppaa.",
    "Vain ollessani navetassa.",
    "Jos olen uimassa miesseurassa."
];
