import * as React from "react";

export const questions = [
    "Välitätkö siitä, mitä muut sinusta puhuvat?",
    "Niistätkö sinä koskaan nenääsi?",
    "Oletko koskaan ollut putkassa?",
    "Kuvitteletko koskaan olevasi Tarzan?",
    "Uskotko, että joulupukki on olemassa?",
    "Kadehditko sinä toisia ihmisiä?",
    "Onko sinulla ollut milloinkaan intohimo kasvattaa viiksiä?",
    "Paleletko sinä nukkuessasi yhdellä viltillä?",
    "Miten tai missä olet ajatellut viettää elämäsi vanhuuden päivät?",
    "Kinaatko sinä vastaan, vaikka olisitkin väärässä?",
    "Leikitkö sinä tinasotamiehillä?",
    "Oletko vihainen, jos satut saamaan korvapuustin?",
    "Juotko mielelläsi kirnupiimää?",
    "Oletkos koskaan leikkinyt vähän tärähtänyttä?",
    "Pelkäätkö olla yksin pimeässä?",
    "Oletko koittanut kurnuttaa niinkuin sammakko?",
    "Pelkäätkö sinä mörköjä?",
    "Olenko minä mielestäsi tyhmä?",
    "Milloin seurustelet mieluiten tyttöjen kanssa?",
    "Osaatko sanoa takaperin »innostunut sonni»",
    "Milloin tunnet olevasi kuin kotonasi?",
    "Onko sinusta laiskottelu mukavaa?",
    "Onko sinusta hienoa puhua kontinkieltä?",
    "Tekeekö mielesi joskus näyttää oikein pitkää nenää?",
    "Tanssitko sinä mielelläsi kiperää polkkaa?",
    "Puhutko sinä unissasi?",
    "Luuletko, että hätävale voisi joskus auttaa?",
    "Voitko syödä yhteen menoon tusinan pannukakkuja?",
    "Liikuskeletko koskaan paitasillasi?",
    "Osaatko viheltää nuotin mukaan?",
    "Ajatteletko sinä koskaan läsnäolijoista hyvää?",
    "Luuletko olevasi viisaampi kuin Tietosanakirja?",
    "Oletko koskaan harrastanut syvämietteistä filosofiaa?",
    "Tekeekö mielesi joskus puhaltaa saippuakuplia?",
    "Oletko saita?",
    "Kuunteletko mielelläsi mandoliinin soittoa?",
    "Oletko joutunut ikävyyksiin liian puheliaisuutesi takia?",
    "Oletko tuntenut joskus olevasi oikealla alalla?",
    "Sepitätkö itse runoja?",
    "Oletko kerännyt joskus kasiaisia?",
    "Onko sinulla tapana syödä ahmimalla?",
    "Kuulutko sinä niihin, jotka ruopivat sormillaan niskaansa nenän kautta?",
    "Voiko mielestäsi käyttää mustien sukkien kanssa valkoisia kumitossuja?",
    "Pidätkö sinä villaisia alushousuja?",
    "Suututko, jos sinua sanotaan aasiksi?",
    "Kuunteletko sinä mielelläsi haitarinsoittoa?",
    "Pidätkö sinä ruutanoitten onkimisesta?",
    "Luuletko, että pienet nokkaunet ovat joskus paikallaan?",
    "Pesetkö sinä koskaan vapaaehtoisesti kasvosi?",
    "Kuunteletko mielelläsi pikkulasten parkumista?",
    "Uskotko sinä kummituksiin?",
    "Tuntuuko sinusta joskus, kuin olisist kyllästynyt elämääsi?",
    "Oletko vihainen, jos satut saamaan korvapuustin?",
    "Sairastatko koskaan päänsärkyä?",
    "Tuntuuko sinusta koulunkäynti kuivalta?",
    "Oletko toivonut olevasi joku toinen kuin mikä olet?",
    "Minkälaisessa tilanteessa tunnet olevasi kaikkein rohkein?",
    "Pidätkö sinä Paksukaista kauniina?",
    "Pelkäätkö saavasi helposti auringonpistoksen?",
    "Juotko sinä koskaan mukillista vettä yhteen menoon?",
    "Suututko helposti?",
    "Oletko saanut joskus tukkapöllyä tytöiltä?",
    "Tuleeko sinulle joskus mieleen läimäyttää jotakuta vasten taulua?",
    "Oletko hyvällä tuulella herätessäsi?",
    "Kuljeskeletko mielelläsi aamutohveleissa?",
    "Et suinkaan polta vain kessuja?",
    "Onko sinusta maailma toisinaan tuntunut perin ikävältä paikalta?",
    "Kutiatko sinä helposti?",
    "Uskotko ihan kaikki mitä sinulle sanotaan?",
    "Pidätkö sinä kehumisesta?",
    "Leikitkö toisinaan olevasi elokuvatähti?",
    "Uitko sinä mielelläsi?",
    "Paukutteletko sinä koskaan koiranpommeilla?",
    "Milloin sinusta tikkukaramelli on parempi kuin sikaari?",
    "Matkitko toisia ihmisiä niinkuin apina?",
    "Onko sinulla toisinaan vaivaa liikavarpaista?",
    "Teetkö sinä joskus hyviä päätöksiä?"
];


